
import { Category, Trend, Source, TimeFrame } from './types';
import { Terminal, Activity, ShoppingCart, Briefcase, Github, Twitter, Youtube, TrendingUp, Globe, Database, MessageCircle, FileText, Linkedin, Coins } from 'lucide-react';
import React from 'react';

export const CATEGORY_CONFIG = {
  [Category.CODE]: {
    color: 'text-nexus-code',
    bg: 'bg-nexus-code',
    border: 'border-nexus-code',
    icon: <Terminal className="w-4 h-4" />,
    label: 'Code & Tech',
    gradient: 'from-cyan-500/20 to-blue-600/5'
  },
  [Category.SOCIAL]: {
    color: 'text-nexus-social',
    bg: 'bg-nexus-social',
    border: 'border-nexus-social',
    icon: <Activity className="w-4 h-4" />,
    label: 'Social & Virality',
    gradient: 'from-fuchsia-500/20 to-purple-600/5'
  },
  [Category.MARKET]: {
    color: 'text-nexus-market',
    bg: 'bg-nexus-market',
    border: 'border-nexus-market',
    icon: <ShoppingCart className="w-4 h-4" />,
    label: 'Market & Consumer',
    gradient: 'from-amber-500/20 to-orange-600/5'
  },
  [Category.BUSINESS]: {
    color: 'text-nexus-biz',
    bg: 'bg-nexus-biz',
    border: 'border-nexus-biz',
    icon: <Briefcase className="w-4 h-4" />,
    label: 'Business & Money',
    gradient: 'from-emerald-500/20 to-green-600/5'
  },
  [Category.CRYPTO]: {
    color: 'text-nexus-crypto',
    bg: 'bg-nexus-crypto',
    border: 'border-nexus-crypto',
    icon: <Coins className="w-4 h-4" />,
    label: 'Crypto & Memes',
    gradient: 'from-violet-500/20 to-purple-600/5'
  },
};

// Helper to generate multi-timeframe sparklines
export const generateSparkline = (): Record<TimeFrame, { value: number }[]> => {
  const createSeries = (points: number, volatility = 20) => {
    let current = 50;
    return Array.from({ length: points }, () => {
      current = Math.max(10, Math.min(100, current + (Math.random() - 0.5) * volatility));
      return { value: Math.floor(current) };
    });
  };

  return {
    '1H': createSeries(12, 15),
    '6H': createSeries(18, 20),
    '24H': createSeries(24, 25),
    '7D': createSeries(14, 40),
    '1M': createSeries(30, 50),
  };
};

// Helper to generate relative timestamps
const NOW = Date.now();
const subHours = (h: number) => NOW - (h * 60 * 60 * 1000);

// Reputation = Reliability weight for the algorithm
export const MOCK_SOURCES: Source[] = [
  { id: 'gh', name: 'GitHub', category: 'Code', status: 'online', signalsToday: 1240, intensity: 95, reputation: 0.95 },
  { id: 'tt', name: 'TikTok', category: 'Social', status: 'online', signalsToday: 8500, intensity: 88, reputation: 0.65 },
  { id: 'yt', name: 'YouTube', category: 'Social', status: 'online', signalsToday: 3400, intensity: 76, reputation: 0.75 },
  { id: 'rd', name: 'Reddit', category: 'Social', status: 'delay', signalsToday: 5600, intensity: 65, reputation: 0.70 },
  { id: 'dex', name: 'DexScreener', category: 'Crypto', status: 'online', signalsToday: 15000, intensity: 98, reputation: 0.99 },
  { id: 'x', name: 'Twitter / X', category: 'Social', status: 'online', signalsToday: 9200, intensity: 92, reputation: 0.60 },
  { id: 'li', name: 'LinkedIn', category: 'Business', status: 'online', signalsToday: 450, intensity: 30, reputation: 0.85 },
  { id: 'amz', name: 'Amazon', category: 'Market', status: 'online', signalsToday: 2100, intensity: 55, reputation: 0.90 },
  { id: 'ark', name: 'Arkham', category: 'Crypto', status: 'online', signalsToday: 400, intensity: 85, reputation: 0.95 },
];

export const MOCK_TRENDS: Trend[] = [
  // CODE TRENDS
  {
    id: 'c1',
    title: 'Claude Prompt Injection',
    description: 'New method for bypassing AI safety filters circulating on GitHub.',
    category: Category.CODE,
    velocity: 98,
    volume: '12k stars',
    source: 'GitHub',
    change: 420,
    tags: ['AI Safety', 'LLM', 'Exploit'],
    novelty: 95,
    signalCount: 12,
    timestamp: '45m ago',
    timestampValue: subHours(0.75),
    sparklineData: generateSparkline(),
    cluster: 'LLM Security',
    isAnomaly: true,
    metrics: { anomalyConfidence: 92, clusterCentrality: 15, contextVelocity: 2.4, volatility: 85 }
  },
  {
    id: 'c2',
    title: 'Rust for Frontend',
    description: 'Rising interest in Rust-based web frameworks like Leptos.',
    category: Category.CODE,
    velocity: 88,
    volume: '5k forks',
    source: 'GitHub',
    change: 120,
    tags: ['Rust', 'WebAssembly', 'Dev'],
    novelty: 70,
    signalCount: 5,
    timestamp: '2h ago',
    timestampValue: subHours(2),
    sparklineData: generateSparkline(),
    cluster: 'WASM Frameworks',
    isAnomaly: true,
    metrics: { anomalyConfidence: 78, clusterCentrality: 45, contextVelocity: 3.1, volatility: 55 }
  },
  {
    id: 'c3',
    title: 'Mojo Language Beta',
    description: 'Sudden spike in repo activity for Modular\'s AI language.',
    category: Category.CODE,
    velocity: 75,
    volume: '8k stars',
    source: 'HackerNews',
    change: 180,
    tags: ['AI', 'Python', 'Compiler'],
    novelty: 85,
    signalCount: 40,
    timestamp: '5h ago',
    timestampValue: subHours(5),
    sparklineData: generateSparkline(),
    cluster: 'AI Infrastructure',
    isAnomaly: false,
    metrics: { anomalyConfidence: 10, clusterCentrality: 80, contextVelocity: 1.5, volatility: 30 }
  },
  {
    id: 'c4',
    title: 'HTMX Adoption Wave',
    description: 'Corporate engineering blogs discussing migration from React to HTMX.',
    category: Category.CODE,
    velocity: 60,
    volume: 'Medium',
    source: 'Twitter/X',
    change: 90,
    tags: ['Web', 'HTMX', 'Backend'],
    novelty: 40,
    signalCount: 15,
    timestamp: '18h ago',
    timestampValue: subHours(18),
    sparklineData: generateSparkline(),
    cluster: 'Low-JS Web',
    isAnomaly: false,
    metrics: { anomalyConfidence: 5, clusterCentrality: 95, contextVelocity: 1.1, volatility: 15 }
  },
  {
    id: 'c5',
    title: 'Local Llama 3 Hosting',
    description: 'New quantization methods allowing Llama 3 on 8GB VRAM.',
    category: Category.CODE,
    velocity: 92,
    volume: 'High',
    source: 'Reddit',
    change: 300,
    tags: ['LocalLLM', 'AI', 'Hardware'],
    novelty: 60,
    signalCount: 85,
    timestamp: '1d ago',
    timestampValue: subHours(24),
    sparklineData: generateSparkline(),
    cluster: 'Local AI',
    isAnomaly: false,
    metrics: { anomalyConfidence: 20, clusterCentrality: 90, contextVelocity: 2.8, volatility: 45 }
  },
  {
    id: 'c6',
    title: 'Bun 1.2 Benchmarks',
    description: 'Controversial benchmarks claiming 5x Node.js speed.',
    category: Category.CODE,
    velocity: 80,
    volume: 'Viral',
    source: 'Twitter/X',
    change: 150,
    tags: ['Runtime', 'JS', 'Performance'],
    novelty: 50,
    signalCount: 60,
    timestamp: '2d ago',
    timestampValue: subHours(48),
    sparklineData: generateSparkline(),
    cluster: 'JS Runtimes',
    isAnomaly: false,
    metrics: { anomalyConfidence: 30, clusterCentrality: 85, contextVelocity: 1.4, volatility: 60 }
  },

  // SOCIAL TRENDS
  {
    id: 's1',
    title: 'Silent Walking',
    description: 'TikTok trend about walking without podcasts or music. Mental health angle.',
    category: Category.SOCIAL,
    velocity: 85,
    volume: '45M views',
    source: 'TikTok',
    change: 390,
    tags: ['Wellness', 'Lifestyle', 'Viral'],
    novelty: 60,
    signalCount: 24,
    timestamp: '1h ago',
    timestampValue: subHours(1),
    sparklineData: generateSparkline(),
    cluster: 'Digital Detox',
    isAnomaly: false,
    metrics: { anomalyConfidence: 20, clusterCentrality: 90, contextVelocity: 1.8, volatility: 40 }
  },
  {
    id: 's2',
    title: 'Dopamine Detox 2.0',
    description: 'YouTube creators pivoting to extreme digital minimalism content.',
    category: Category.SOCIAL,
    velocity: 92,
    volume: '12M views',
    source: 'YouTube',
    change: 280,
    tags: ['Productivity', 'YouTube', 'Self-Help'],
    novelty: 55,
    signalCount: 32,
    timestamp: '3h ago',
    timestampValue: subHours(3),
    sparklineData: generateSparkline(),
    cluster: 'Digital Detox',
    isAnomaly: false,
    metrics: { anomalyConfidence: 15, clusterCentrality: 95, contextVelocity: 2.1, volatility: 30 }
  },
  {
    id: 's3',
    title: '"Old Money" Aesthetic',
    description: 'Resurgence of quiet luxury fashion content on Instagram Reels.',
    category: Category.SOCIAL,
    velocity: 65,
    volume: '8M Posts',
    source: 'Instagram',
    change: 80,
    tags: ['Fashion', 'Lifestyle', 'GenZ'],
    novelty: 20,
    signalCount: 120,
    timestamp: '20h ago',
    timestampValue: subHours(20),
    sparklineData: generateSparkline(),
    cluster: 'Aesthetics',
    isAnomaly: false,
    metrics: { anomalyConfidence: 5, clusterCentrality: 98, contextVelocity: 1.0, volatility: 10 }
  },
  {
    id: 's4',
    title: 'Monk Mode Challenge',
    description: 'Extreme productivity protocol gaining traction in entrepreneurial circles.',
    category: Category.SOCIAL,
    velocity: 78,
    volume: 'High',
    source: 'Twitter/X',
    change: 210,
    tags: ['Productivity', 'Grindset', 'Biz'],
    novelty: 50,
    signalCount: 45,
    timestamp: '1d ago',
    timestampValue: subHours(26),
    sparklineData: generateSparkline(),
    cluster: 'High Performance',
    isAnomaly: false,
    metrics: { anomalyConfidence: 25, clusterCentrality: 88, contextVelocity: 1.9, volatility: 35 }
  },
  {
    id: 's5',
    title: 'Raw Milk Debates',
    description: 'Health influencers promoting raw dairy vs establishment warnings.',
    category: Category.SOCIAL,
    velocity: 82,
    volume: 'Viral',
    source: 'TikTok',
    change: 350,
    tags: ['Health', 'Diet', 'Controversial'],
    novelty: 75,
    signalCount: 200,
    timestamp: '1.5d ago',
    timestampValue: subHours(36),
    sparklineData: generateSparkline(),
    cluster: 'Alt-Health',
    isAnomaly: true,
    metrics: { anomalyConfidence: 60, clusterCentrality: 70, contextVelocity: 2.5, volatility: 80 }
  },
  {
    id: 's6',
    title: 'NPC Streaming 2.0',
    description: 'Evolution of NPC streaming into interactive horror games.',
    category: Category.SOCIAL,
    velocity: 89,
    volume: 'Very High',
    source: 'TikTok',
    change: 400,
    tags: ['Gaming', 'Live', 'Strange'],
    novelty: 90,
    signalCount: 50,
    timestamp: '30m ago',
    timestampValue: subHours(0.5),
    sparklineData: generateSparkline(),
    cluster: 'Live Interaction',
    isAnomaly: true,
    metrics: { anomalyConfidence: 85, clusterCentrality: 40, contextVelocity: 3.5, volatility: 90 }
  },

  // MARKET TRENDS
  {
    id: 'm1',
    title: 'Portable AI Pendants',
    description: 'Hardware startups launching wearable AI pins. High search volume.',
    category: Category.MARKET,
    velocity: 72,
    volume: '85k searches',
    source: 'Google Trends',
    change: 150,
    tags: ['Hardware', 'Wearables', 'Tech'],
    novelty: 80,
    signalCount: 8,
    timestamp: '6h ago',
    timestampValue: subHours(6),
    sparklineData: generateSparkline(),
    cluster: 'Wearable AI',
    isAnomaly: false,
    metrics: { anomalyConfidence: 35, clusterCentrality: 75, contextVelocity: 1.2, volatility: 60 }
  },
  {
    id: 'm2',
    title: 'Smart Rings',
    description: 'Cheap Oura ring competitors flooding the market from Shenzhen.',
    category: Category.MARKET,
    velocity: 84,
    volume: 'High',
    source: 'Alibaba',
    change: 280,
    tags: ['Hardware', 'Health', 'Dropship'],
    novelty: 40,
    signalCount: 150,
    timestamp: '12h ago',
    timestampValue: subHours(12),
    sparklineData: generateSparkline(),
    cluster: 'Health Tech',
    isAnomaly: false,
    metrics: { anomalyConfidence: 10, clusterCentrality: 85, contextVelocity: 1.6, volatility: 25 }
  },
  {
    id: 'm3',
    title: 'Mushroom Coffee',
    description: 'Functional beverage market exploding with Lion\'s Mane blends.',
    category: Category.MARKET,
    velocity: 55,
    volume: 'Steady',
    source: 'Amazon',
    change: 60,
    tags: ['Food', 'Health', 'Nootropics'],
    novelty: 30,
    signalCount: 400,
    timestamp: '2d ago',
    timestampValue: subHours(48),
    sparklineData: generateSparkline(),
    cluster: 'Functional Foods',
    isAnomaly: false,
    metrics: { anomalyConfidence: 5, clusterCentrality: 95, contextVelocity: 0.8, volatility: 10 }
  },
  {
    id: 'm4',
    title: 'E-Ink Monitors',
    description: 'Niche demand for high-refresh rate E-Ink screens for coding.',
    category: Category.MARKET,
    velocity: 68,
    volume: 'Niche',
    source: 'YouTube',
    change: 120,
    tags: ['Hardware', 'Productivity', 'Office'],
    novelty: 70,
    signalCount: 12,
    timestamp: '3d ago',
    timestampValue: subHours(72),
    sparklineData: generateSparkline(),
    cluster: 'Niche Peripherals',
    isAnomaly: false,
    metrics: { anomalyConfidence: 20, clusterCentrality: 60, contextVelocity: 1.1, volatility: 30 }
  },
  {
    id: 'm5',
    title: 'Hydrogen Water Bottles',
    description: 'Pseudo-scientific health gadget going viral on Instagram.',
    category: Category.MARKET,
    velocity: 95,
    volume: 'Exploding',
    source: 'Instagram',
    change: 500,
    tags: ['Health', 'Gadget', 'Scam?'],
    novelty: 60,
    signalCount: 80,
    timestamp: '5h ago',
    timestampValue: subHours(5),
    sparklineData: generateSparkline(),
    cluster: 'Viral Gadgets',
    isAnomaly: true,
    metrics: { anomalyConfidence: 70, clusterCentrality: 50, contextVelocity: 4.0, volatility: 85 }
  },
  {
    id: 'm6',
    title: 'Bamboo Keyboards',
    description: 'Eco-friendly mechanical keyboards gaining traction.',
    category: Category.MARKET,
    velocity: 45,
    volume: 'Low',
    source: 'Pinterest',
    change: 40,
    tags: ['Eco', 'Tech', 'Design'],
    novelty: 50,
    signalCount: 8,
    timestamp: '4d ago',
    timestampValue: subHours(96),
    sparklineData: generateSparkline(),
    cluster: 'Sustainable Tech',
    isAnomaly: false,
    metrics: { anomalyConfidence: 10, clusterCentrality: 70, contextVelocity: 0.5, volatility: 15 }
  },

  // BUSINESS TRENDS
  {
    id: 'b1',
    title: 'Micro-SaaS Acquisition',
    description: 'Surge in platforms buying tiny SaaS projects under $5k MRR.',
    category: Category.BUSINESS,
    velocity: 65,
    volume: 'High Activity',
    source: 'IndieHackers',
    change: 210,
    tags: ['SaaS', 'Exit', 'Investing'],
    novelty: 40,
    signalCount: 15,
    timestamp: '1d ago',
    timestampValue: subHours(24),
    sparklineData: generateSparkline(),
    cluster: 'Private Equity',
    isAnomaly: false,
    metrics: { anomalyConfidence: 10, clusterCentrality: 88, contextVelocity: 0.9, volatility: 20 }
  },
  {
    id: 'b2',
    title: 'Newsletter Flipping',
    description: 'Buying inactive newsletters, warming IPs, and reselling.',
    category: Category.BUSINESS,
    velocity: 70,
    volume: 'Medium',
    source: 'Twitter/X',
    change: 140,
    tags: ['Media', 'Flipping', 'Email'],
    novelty: 65,
    signalCount: 20,
    timestamp: '2d ago',
    timestampValue: subHours(48),
    sparklineData: generateSparkline(),
    cluster: 'Digital Assets',
    isAnomaly: false,
    metrics: { anomalyConfidence: 15, clusterCentrality: 80, contextVelocity: 1.3, volatility: 40 }
  },
  {
    id: 'b3',
    title: 'AI Agency Saturation',
    description: 'Reports of price crashing for generic AI automation agencies.',
    category: Category.BUSINESS,
    velocity: 88,
    volume: 'High',
    source: 'LinkedIn',
    change: -20,
    tags: ['Agency', 'AI', 'B2B'],
    novelty: 10,
    signalCount: 200,
    timestamp: '4h ago',
    timestampValue: subHours(4),
    sparklineData: generateSparkline(),
    cluster: 'Service Biz',
    isAnomaly: false,
    metrics: { anomalyConfidence: 5, clusterCentrality: 95, contextVelocity: 0.8, volatility: 30 }
  },
  {
    id: 'b4',
    title: 'Faceless YouTube Automation',
    description: 'Renewed interest due to AI video generators like Sora/Veo.',
    category: Category.BUSINESS,
    velocity: 94,
    volume: 'Very High',
    source: 'YouTube',
    change: 320,
    tags: ['Passive Income', 'AI Video', 'Content'],
    novelty: 60,
    signalCount: 150,
    timestamp: '1h ago',
    timestampValue: subHours(1),
    sparklineData: generateSparkline(),
    cluster: 'Content Automation',
    isAnomaly: false,
    metrics: { anomalyConfidence: 20, clusterCentrality: 90, contextVelocity: 2.2, volatility: 50 }
  },
  {
    id: 'b5',
    title: 'Faceless TikTok Shop',
    description: 'Using AI avatars to sell generic products on TikTok Shop.',
    category: Category.BUSINESS,
    velocity: 98,
    volume: 'Exploding',
    source: 'Twitter/X',
    change: 600,
    tags: ['Ecom', 'AI', 'TikTok'],
    novelty: 90,
    signalCount: 80,
    timestamp: '2h ago',
    timestampValue: subHours(2),
    sparklineData: generateSparkline(),
    cluster: 'Social Commerce',
    isAnomaly: true,
    metrics: { anomalyConfidence: 80, clusterCentrality: 60, contextVelocity: 4.5, volatility: 95 }
  },
  {
    id: 'b6',
    title: 'High-Ticket Affiliate',
    description: 'Shift from low-ticket amazon links to high-value software referrals.',
    category: Category.BUSINESS,
    velocity: 50,
    volume: 'Steady',
    source: 'IndieHackers',
    change: 40,
    tags: ['Affiliate', 'Marketing', 'Sales'],
    novelty: 20,
    signalCount: 10,
    timestamp: '5d ago',
    timestampValue: subHours(120),
    sparklineData: generateSparkline(),
    cluster: 'Affiliate Marketing',
    isAnomaly: false,
    metrics: { anomalyConfidence: 5, clusterCentrality: 90, contextVelocity: 0.6, volatility: 10 }
  }
];

export const SOURCES = [
  { name: 'GitHub', icon: <Github size={14} /> },
  { name: 'Twitter/X', icon: <Twitter size={14} /> },
  { name: 'YouTube', icon: <Youtube size={14} /> },
  { name: 'Reddit', icon: <MessageCircle size={14} /> },
  { name: 'ProductHunt', icon: <TrendingUp size={14} /> },
  { name: 'DexScreener', icon: <Coins size={14} /> },
  { name: 'HackerNews', icon: <Terminal size={14} /> },
  { name: 'TikTok', icon: <Activity size={14} /> },
  { name: 'LinkedIn', icon: <Linkedin size={14} /> },
  { name: 'Medium', icon: <FileText size={14} /> },
  { name: 'Substack', icon: <FileText size={14} /> },
  { name: 'Telegram', icon: <MessageCircle size={14} /> },
  { name: 'Discord', icon: <MessageCircle size={14} /> },
  { name: 'Google Trends', icon: <TrendingUp size={14} /> },
  { name: 'Amazon', icon: <ShoppingCart size={14} /> },
  { name: 'Shopify', icon: <Briefcase size={14} /> },
  { name: 'Gumroad', icon: <ShoppingCart size={14} /> },
  { name: 'HuggingFace', icon: <Database size={14} /> },
  { name: 'Arxiv', icon: <FileText size={14} /> },
  { name: '4Chan', icon: <MessageCircle size={14} /> },
];
